//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.Objects;

namespace Chapter2ConsoleApp
{
    using System.Data.Entity;

    public partial class SampleEntities : ObjectContext
    {
        public SampleEntities(string connString = "name=SampleEntities")
            : base(connString)
        {
        }

     

        public DbSet<Address> Addresses { get; set; }

        public DbSet<Contact> Contacts { get; set; }

        private ObjectSet<Contact> _contacts;

        public ObjectSet<Contact> ContactsObjectSet
        {
            get
            {
                if (_contacts == null)
                {
                    _contacts = base.CreateObjectSet<Contact>();
                }
                return _contacts;
            }
        }

        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<vOfficeAddress> vOfficeAddresses { get; set; }
    }
}
